name: flutter_project
description: "A testing of a new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.3
  google_sign_in: ^6.2.1
  http: ^1.2.1
  intl: ^0.18.0
  firebase_database: ^10.4.11
  get: ^4.6.6
  awesome_notifications_core: ^0.9.0
  awesome_notifications: ^0.8.2
  firebase_messaging: ^14.8.1
  firebase_analytics_web: ^0.5.7+1
  firebase_analytics: ^10.10.1
  flutter_image_slideshow: any
  url_launcher: ^6.2.6
  cloud_firestore: ^4.17.2
  dash_chat_2: ^0.0.20
  chat_gpt_sdk: ^2.2.5
  flutter_gemini: ^2.0.3
  image_picker: ^1.1.0
  sqflite: ^2.3.3+1
  firebase_storage: ^11.7.4
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  flutter_rating_bar: ^4.0.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_dotenv: ^5.1.0
  midtrans_sdk: ^0.4.0
  fluttertoast: ^8.2.5
  shimmer_pro: ^0.0.6
  shimmer: ^3.0.0
  draggable_fab: ^0.1.4
  tutorial_coach_mark: ^1.2.11
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/app_icon.png
    - .env

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600
