// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGPLA6TNovCK7YMFVDSSSs31_JxBnZjPQ',
    appId: '1:286340514293:web:928792ba4be12e0186e0bc',
    messagingSenderId: '286340514293',
    projectId: 'loginsignupta-prototype',
    authDomain: 'loginsignupta-prototype.firebaseapp.com',
    databaseURL: 'https://loginsignupta-prototype-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loginsignupta-prototype.appspot.com',
    measurementId: 'G-F9D529WRM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZllPP5leFgznOCXo3iIxYmO9-Q8upDj0',
    appId: '1:286340514293:android:232e3d670d5880ff86e0bc',
    messagingSenderId: '286340514293',
    projectId: 'loginsignupta-prototype',
    databaseURL: 'https://loginsignupta-prototype-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loginsignupta-prototype.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsg2Yxm8q6yVG083EM69djR1nc4_wjN0A',
    appId: '1:286340514293:ios:e06bab0d770a348886e0bc',
    messagingSenderId: '286340514293',
    projectId: 'loginsignupta-prototype',
    databaseURL: 'https://loginsignupta-prototype-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loginsignupta-prototype.appspot.com',
    androidClientId: '286340514293-gqfsrt668iedqo0ff10bp7ql3fq428f7.apps.googleusercontent.com',
    iosClientId: '286340514293-s87q5nera1b602jes5av1jk3jo5ukv2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );
}
